AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''
  RDSHost:
    Type: String
    Description: RDS host name.
    Default: 'sheet-pricelist.cluster-cmf3mqmfzrcu.us-east-2.rds.amazonaws.com'
  RDSDBName:
    Type: String
    Description: RDS DB name.
    Default: 'pricelist'
  RDSDBUsername:
    Type: String
    Description: RDS DB username.
    Default: 'admin'
  RDSDBPassword:
    Type: String
    Description: RDS DB password.
    Default: 'password'

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole
    Environment:
      Variables:
        RDS_HOST: !Ref RDSHost
        RDS_DB_NAME: !Ref RDSDBName
        RDS_DB_USERNAME: !Ref RDSDBUsername
        RDS_DB_PASSWORD: !Ref RDSDBPassword

Resources:
  Utils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: utils
      LayerName: layer-utils
      Description: Dependencies and handler common for functions.
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7 
  Categories:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-Categories'
      CodeUri: handlers/categories
      Handler: index.handler
      Runtime: python3.7
      Layers:
        - !Ref Utils
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: post
  Environment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'awscodestar-${ProjectId}-lambda-Categories'
      CodeUri: handlers/environment
      Handler: index.handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /environment
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /environment
            Method: post
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'