AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: 'dev'
  # TABLES
  CategoriesTableName:
    Type: String
    Description: The name for categories table in DynamoDB
    Default: 'Categories'
  ItemsTableName:
    Type: String
    Description: The name for items table in DynamoDB
    Default: 'Items'

Globals:
  Function:
    Environment:
      Variables:
        CATEGORIES_TABLE: !Ref CategoriesTableName
        ITEMS_TABLE: !Ref ItemsTableName

Resources:
  # API
  PricelistApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: sheet-pricelist-api
      StageName: !Ref Stage
      EndpointConfiguration: REGIONAL
      Auth:
        AddDefaultAuthorizerToCorsPreflight: False
        ApiKeyRequired: False
  # TABLES
  CategoriesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Ref CategoriesTableName
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: categoryId
          AttributeType: S
        - AttributeName: created
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes: 
        - IndexName: category
          KeySchema: 
            - AttributeName: categoryId
              KeyType: HASH
            - AttributeName: created
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
      TableName: !Ref ItemsTableName
  # LAYERS
  Utils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: utils
      LayerName: layer-utils
      Description: Dependencies and handler common for functions.
      CompatibleRuntimes:
        - python3.7
    Metadata:
      BuildMethod: python3.7 
  # METHODS
  Categories:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'sheet-pricelist-Categories-${Stage}'
      CodeUri: handlers/categories
      Handler: index.handler
      Runtime: python3.7
      Layers:
        - !Ref Utils
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: get
            RestApiId: !Ref PricelistApi
        PostEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: post
            RestApiId: !Ref PricelistApi
        PutEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: put
            RestApiId: !Ref PricelistApi
        DeleteEvent:
          Type: Api
          Properties:
            Path: /categories
            Method: delete
            RestApiId: !Ref PricelistApi
  Items:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'sheet-pricelist-Items-${Stage}'
      CodeUri: handlers/items
      Handler: index.handler
      Runtime: python3.7
      Layers:
        - !Ref Utils
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /items
            Method: get
            RestApiId: !Ref PricelistApi
        PostEvent:
          Type: Api
          Properties:
            Path: /items
            Method: post
            RestApiId: !Ref PricelistApi
        PutEvent:
          Type: Api
          Properties:
            Path: /items
            Method: put
            RestApiId: !Ref PricelistApi
        DeleteEvent:
          Type: Api
          Properties:
            Path: /items
            Method: delete
            RestApiId: !Ref PricelistApi
  # ROLES
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'sheet-pricelist-Execution-${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonDynamoDBFullAccess'